### PR TITLE
Easy Emoticon Feature: Added command list modal functionality in version 0.7.8 

### PR DESCRIPTION
**Pull request by minnieoo**
This PR adds the functionality to Easy Emoticon of a command panel that can be summoned with /help or /commands, which conveniently allows you to scroll through the list of commands on Kbin through a modal, rather than rely on memory or an external document like before.

Updated the changes to be on the testing branch. @aclist not sure if i did this right, but i am hoping so 
image

### CODE REVIEW

**Comment by aclist** [comment]
Almost perfect: you inadvertently inserted the issue templates directory from the main branch, but it is fine, I deleted it. This PR is clean now and will approve. Thank you!

**Comment by aclist** [comment]
It looks like you escaped a backslash in the /2cheer emoticon. Is this intentional? It is printing out like this:

```
( ´▽\`）o自自o（´▽` ） 
```

**Comment by minnieoo** [comment]
@aclist , yes thats intentional. or without that it will format as code on kbin. with it, it escapes that. also im glad to see this was mostly done right! 
image

i really dont know how the issue templates thing happened, but it refused to let me go on without it for some reason, but it was something i did wrong im sure. still winging this lol

**Comment by aclist** [comment]
Makes sense, I didn't actually try pasting it, just looked at it in the editor.

**Pull request merged**
